In [1]:
library(M4comp2018)
library(tsfeatures)

Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo

In [2]:
Quarterly_M4 <- Filter(function(l) l$period == "Quarterly", M4)

In [4]:
data=Quarterly_M4

In [5]:
data[[1]]

$st
[1] "Q1"

$x
         Qtr1     Qtr2     Qtr3     Qtr4
2005 7407.412 7528.566 7374.709 7395.515
2006 7654.008 7686.848 7578.191 7904.377
2007 7744.049 7889.909 7572.111 7526.693
2008 7331.846 7433.141 7235.135 7278.007
2009 6560.231 6958.547 6635.482 6588.665
2010 6679.074 6702.856 6636.516 6766.947
2011 6818.167

$n
[1] 25

$type
[1] Macro
Levels: Demographic Finance Industry Macro Micro Other

$h
[1] 8

$period
[1] Quarterly
Levels: Daily Hourly Monthly Quarterly Weekly Yearly

$xx
         Qtr1     Qtr2     Qtr3     Qtr4
2011          6790.644 6598.952 6608.527
2012 6765.914 6992.949 6931.539 7161.241
2013 6981.304

$pt_ff
          [,1]     [,2]     [,3]     [,4]     [,5]     [,6]     [,7]     [,8]
 [1,] 6910.539 6777.863 6900.975 6894.792 7011.891 6883.856 6995.383 6979.321
 [2,] 6819.817 6794.861 6805.209 6789.357 6805.336 6778.025 6787.302 6769.995
 [3,] 6789.597 6793.237 6792.416 6790.751 6787.102 6782.495 6776.819 6770.433
 [4,] 6793.581 6780.154 6790.006 6790.006 6790.006 6776.779 6776.779 6790.006
 [5,] 6782.019 6778.620 6770.530 6764.773 6757.977 6751.757 6745.335 6739.082
 [6,] 6788.504 6784.946 6781.503 6778.175 6774.958 6771.849 6768.844 6765.938
 [7,] 6746.255 6740.180 6724.010 6713.394 6698.892 6687.229 6674.119 6662.216
 [8,] 6755.698 6731.746 6707.794 6683.842 6659.890 6635.938 6611.986 6588.034
 [9,] 6962.080 6770.304 6895.577 6763.815 6953.203 6789.041 6907.601 6782.228
[10,] 6766.538 6752.017 6737.421 6722.750 6708.002 6693.177 6678.272 6663.288
[11,] 6766.206 6751.494 6736.707 6721.843 6706.902 6691.882 6676.784 6661.604
[12,] 6766.782 6732.112 6744.655 6713.751 6732.235 6696.171 6709.382 6678.158
[13,] 6787.009 6779.893 6773.008 6766.351 6759.917 6753.699 6747.688 6741.878
[14,] 6810.790 6737.191 6794.359 6753.718 6823.566 6744.379 6804.229 6762.301
[15,] 6785.864 6776.924 6788.738 6790.171 6790.430 6790.583 6790.610 6790.610
[16,] 6929.715 6795.869 6871.668 6796.186 6929.715 6795.869 6871.668 6796.186
[17,] 6789.598 6789.598 6789.598 6789.598 6789.598 6789.598 6789.598 6789.598
[18,] 6749.708 6725.756 6701.804 6677.852 6653.900 6629.948 6605.996 6582.044
[19,] 6840.474 6888.342 6932.956 6974.966 7014.894 7053.156 7090.085 7125.948
[20,] 6793.581 6805.382 6799.717 6802.437 6801.131 6801.758 6801.457 6801.602
[21,] 6791.500 6795.433 6793.545 6794.451 6794.016 6794.225 6794.125 6794.173
[22,] 6832.049 6880.861 6919.911 6951.151 6976.143 6996.136 7012.131 7024.927
[23,] 6790.003 6790.003 6790.003 6790.003 6790.003 6790.003 6790.003 6790.003
[24,] 6824.526 6669.602 6764.268 6750.169 6863.630 6697.869 6785.078 6765.315
[25,] 6705.321 6840.413 6744.351 6699.574 6603.135 6565.194 6578.389 6520.277

$up_ff
          [,1]     [,2]     [,3]      [,4]      [,5]      [,6]      [,7]
 [1,] 7477.076 7476.992 7637.802  7633.223  7882.427  7837.487  7997.786
 [2,] 7336.991 7516.942 7738.578  7937.224  8104.029  8258.964  8021.979
 [3,]       NA       NA       NA        NA        NA        NA        NA
 [4,]       NA       NA       NA        NA        NA        NA        NA
 [5,] 7179.701 7235.415 7306.598  7352.565  7432.121  7475.371  7519.757
 [6,] 7207.010 7267.501 7327.338  7391.922  7444.729  7495.929  7544.086
 [7,]       NA       NA       NA        NA        NA        NA        NA
 [8,]       NA       NA       NA        NA        NA        NA        NA
 [9,] 7308.093 7184.770 7365.786  7253.481  7474.177  7308.044  7441.981
[10,]       NA       NA       NA        NA        NA        NA        NA
[11,]       NA       NA       NA        NA        NA        NA        NA
[12,] 7144.476 7145.257 7211.166  7211.144  7284.194  7278.237  7327.826
[13,] 7247.049 7375.820 7395.014  7437.536  7525.561  7615.260  7617.548
[14,]       NA       NA       NA        NA        NA        NA        NA
[15,]       NA       NA       NA        NA        NA        NA        NA
[16,]       NA       NA       NA        NA        NA        NA        NA
[17,]       NA       NA       NA        NA        NA        NA        NA
[18,]       NA       NA       NA        NA        NA        NA        NA
[19,]       NA       NA       NA        NA        NA        NA        NA
[20,] 7194.646 7257.429 7342.785  7403.076  7462.941  7515.649  7565.617
[21,]       NA       NA       NA        NA        NA        NA        NA
[22,]       NA       NA       NA        NA        NA        NA        NA
[23,] 7183.533 7265.626 7335.529  7397.463  7453.664  7505.483  7553.814
[24,] 9542.424 9550.473 9846.223 10047.634 10540.533 10631.912 10967.118
[25,] 8066.632 8605.533 8586.441  8706.095  8799.127  8876.063  9140.234
           [,8]
 [1,]  8013.437
 [2,]  8129.073
 [3,]        NA
 [4,]        NA
 [5,]  7537.348
 [6,]  7589.144
 [7,]        NA
 [8,]        NA
 [9,]  7310.630
[10,]        NA
[11,]        NA
[12,]  7330.969
[13,]  7801.325
[14,]        NA
[15,]        NA
[16,]        NA
[17,]        NA
[18,]        NA
[19,]        NA
[20,]  7612.133
[21,]        NA
[22,]        NA
[23,]  7599.282
[24,] 11179.424
[25,]  9256.937

$low_ff
          [,1]     [,2]     [,3]     [,4]     [,5]     [,6]     [,7]     [,8]
 [1,] 6559.167 6356.408 6366.639 6258.041 6378.689 6238.622 6264.067 6174.994
 [2,] 6302.643 6072.780 5871.841 5641.490 5506.643 5297.087 5552.624 5410.917
 [3,]       NA       NA       NA       NA       NA       NA       NA       NA
 [4,]       NA       NA       NA       NA       NA       NA       NA       NA
 [5,] 6362.270 6279.431 6218.639 6153.109 6064.522 5995.940 5935.121 5929.901
 [6,] 6401.038 6246.261 6194.594 6143.778 6073.986 6007.283 5881.330 5826.091
 [7,]       NA       NA       NA       NA       NA       NA       NA       NA
 [8,]       NA       NA       NA       NA       NA       NA       NA       NA
 [9,] 6632.450 6379.747 6455.385 6307.206 6468.542 6306.896 6411.593 6292.018
[10,]       NA       NA       NA       NA       NA       NA       NA       NA
[11,]       NA       NA       NA       NA       NA       NA       NA       NA
[12,] 6115.466 6111.518 6111.481 6054.334 6036.927 5973.927 5967.947 5909.548
[13,] 6311.303 6350.825 6059.860 6018.112 5973.219 5871.815 5843.908 5772.574
[14,]       NA       NA       NA       NA       NA       NA       NA       NA
[15,]       NA       NA       NA       NA       NA       NA       NA       NA
[16,]       NA       NA       NA       NA       NA       NA       NA       NA
[17,]       NA       NA       NA       NA       NA       NA       NA       NA
[18,]       NA       NA       NA       NA       NA       NA       NA       NA
[19,]       NA       NA       NA       NA       NA       NA       NA       NA
[20,] 6392.515 6353.335 6256.649 6201.798 6139.322 6087.866 6037.297 5991.070
[21,]       NA       NA       NA       NA       NA       NA       NA       NA
[22,]       NA       NA       NA       NA       NA       NA       NA       NA
[23,] 6396.472 6314.379 6244.477 6182.542 6126.342 6074.522 6026.191 5980.723
[24,] 4106.628 3788.731 3682.312 3452.703 3186.728 2763.825 2603.038 2351.205
[25,] 5197.639 5004.597 4540.734 4375.177 4116.526 3925.412 3901.681 3682.056

In [6]:
Feature_extraction=function(data,train_index)
{
    datalength=length(data)
    feature_ep=tsfeatures(data[[1]]$x)
    feature_matrix=matrix(0,datalength,length(feature_ep)+1)
    colnames(feature_matrix)=c(colnames(feature_ep),'length')
    train_matrix <- matrix(0,ncol = 3, nrow =datalength)
    test_matrix <- matrix(0,ncol = 3, nrow =datalength)
    colnames(train_matrix) <- c("user_time", "system_time", "elapsed_time")
    colnames(test_matrix) <- c("user_time", "system_time", "elapsed_time")
    for(i in 1:datalength){
        start_time = Sys.time()
        y =  data[[i]]$x
        features=cbind(as.matrix(tsfeatures(y)),length(y))
        feature_matrix[i,] = features
        end_time = Sys.time()
        if (i %in% train_index) {
                train_matrix[i,] = end_time - start_time
        } else {
                test_matrix[i,] = end_time - start_time
            }
    
}
    return(list(feature_matrix, train_matrix, test_matrix))
    }

In [7]:
set.seed(100)
index = sample(2,length(data),replace = TRUE,prob=c(0.7,0.3))
trainindex=c(1:length(data))[index==1]

In [ ]:
feature_matrix=Feature_extraction(data,trainindex)

In [ ]:
write.csv(feature_matrix,file='Quarterly_features_matrix.csv')